{% metadata_file .yamato_config/config.yml %}
---
build:
  name: Build
  agent:
    type: Unity::VM
    image: core-kaunas/win10-vs2017-dotnetcore:latest
    flavor: m1.large
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

  commands:
    - dotnet restore
    - dotnet build -c Release
    - npm install upm-ci-utils@stable -g --registry https://api.bintray.com/npm/unity/unity-npm
{% for package in packages %}
    - upm-ci package pack --package-path {{ package.path }}
{% endfor %}

  triggers:
    pull_requests:
      - targets:
          only:
            - "master"
    branches:
      only:
      - "master"

  artifacts:
    packman:
      paths:
        - "upm-ci~/**/*"
    binaries:
      paths:
        - "build/bin/**/*"
